### ISSUE TITLE
Menu items are not getting filtered based on the Space Id

### ISSUE THREAD

**Issue by deshetti** [factly/dega-api#58]
Currently, when we retrieve menus it is not filtering based on the space id

**Comment by hetjagani** [comment]
Menu is getting filteres based on "space" provided in header. If not provided then it fetches from all. (This behaviour is same for all the entities)

**Comment by deshetti** [comment]
@fyrepenguin can you please confirm if the above behavior is what you are experiencing?

@hetjagani if space is not provided, what would *all* mean? all the spaces in that organization?

**Comment by hetjagani** [comment]
Now `X-Space` is mandatory header.. If not passed then it throws 401 response. So for every entity we have to pass `X-Space` header and it'll only return based on that space.

**Comment by fyrepenguin** [comment]
When I made this issue I wanted to have a space argument that filters based on space id for menu like the rest of the queries like posts, formats, categories, etc. 

But I just noticed the changes we made this week made the space argument in the queries(posts,formats, categories, tags) completely obsolete. 

Like @hetjagani mentioned, space id is a mandatory field in header now and we're getting the data only from that space, even if we specify other spaceid in query arguments. 

Correct me if I'm wrong @deshetti, But we just wanted to make a default spaceid based on header's 'X-Space', instead of adding spaceid on every query, right? 
And also getting all the organization data if 'X-Space' is not specified and getting data from other spaces if we specify them in the arguments of our queries, right?
